### ISSUE TITLE
When installing from :git, breaks rails

### ISSUE THREAD

**Issue by tavon** [browsermedia/bcms_news#5]
When installing the gem from git, the module breaks as it includes additional files that shouldn't be included in an engine.  The packaged gem works fine as it doesn't include /config.  I'm curious why master includes the /config folder...  Is it necessary for testing?

**Comment by peakpg** [comment]
This is a known issue with pretty much all of the BrowserCMS modules that are bcms-3.3.x compatible. It is for testing purposes. Basically each module is both a gem and rails app all together.

This will be solved when BrowserCMS 3.4 is released. Mountable engines use a 'dummy' Rails app that lives under test. When we upgrade these modules they will use the test/dummy configuration, which should allow for Gemfiles to include these modules via :git or :path.

**Comment by tavon** [comment]
Appreciate the reply... Just want to let you know you're doing an amazing job!  Thank you for being awesome!
