### ISSUE TITLE
undefined method  `copy_migration_file' 

### ISSUE THREAD

**Issue by slayer** [browsermedia/bcms_news#8]
```
 $ rails g cms:install bcms_news
     gemfile  bcms_news
    generate  bcms_news:install
..../lib/ruby/gems/1.9.1/gems/bcms_news-1.2.1/lib/generators/bcms_news/install/install_generator.rb:6:in `<class:InstallGenerator>': undefined method     `copy_migration_file' for BcmsNews::InstallGenerator:Class (NoMethodError)
```

**Comment by peakpg** [comment]
This should be fixed in 1.4.0, though you will need to update to BrowserCMS 3.5.0.rc2 or later to take advantage of it. If you still have issues in the meantime, you can manually copy the migration files and seeds.rb from bcms_news into your project and run them there.
